development:
  adapter: mysql
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  database: astacus_dev
  username: astacus_dev
  password: astacus_dev

test:
  adapter: mysql
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  database: astacus_test
  username: astacus_test
  password: astacus_test

production:
  adapter: mysql
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  database: astacus
  username: astacus
  password: astacus
